name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /opt/android-sdk
      ANDROIDSDK: /opt/android-sdk

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip tar openjdk-17-jdk python3-pip python3-setuptools git wget build-essential libncurses5-dev libffi-dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Download Android SDK Command Line Tools
        run: |
          sudo mkdir -p /opt/android-sdk/cmdline-tools
          sudo wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          sudo unzip cmdline-tools.zip -d /opt/android-sdk/cmdline-tools
          sudo mv /opt/android-sdk/cmdline-tools/cmdline-tools /opt/android-sdk/cmdline-tools/latest
          rm cmdline-tools.zip
          sudo chown -R $USER:$USER /opt/android-sdk

      - name: Install Android SDK Build Tools (includes AIDL)
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --install \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;36.0.0"

          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses --sdk_root=$ANDROID_SDK_ROOT

      - name: Confirm aidl is present
        run: |
          AIDL_PATH="$ANDROID_SDK_ROOT/build-tools/36.0.0/aidl"
          if [ -f "$AIDL_PATH" ]; then
            echo "✅ AIDL located at $AIDL_PATH"
          else
            echo "❌ AIDL not found! Check your sdkmanager install logs."
            exit 1
          fi

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install cython virtualenv buildozer

      - name: Build the APK
        run: |
          export ANDROIDSDK=$ANDROID_SDK_ROOT
          export ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: myapp
          path: bin/*.apk
