name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /tmp/android-sdk
      ANDROIDSDK: /tmp/android-sdk
      PATH: /tmp/android-sdk/build-tools/36.0.0:/tmp/android-sdk/platform-tools:/tmp/android-sdk/cmdline-tools/latest/bin:$PATH

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools git wget build-essential libncurses5-dev tar

      - name: Download Android SDK Command Line Tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
          rm cmdline-tools.zip

      - name: Install Android build tools and platform tools
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --install "platform-tools" "platforms;android-33" "build-tools;36.0.0"
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses --sdk_root=$ANDROID_SDK_ROOT

      - name: Verify aidl presence
        run: |
          ls -l $ANDROID_SDK_ROOT/build-tools/36.0.0/aidl

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install cython virtualenv buildozer

      - name: Initialize Buildozer if needed
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Build the APK
        run: |
          export ANDROIDSDK=/tmp/android-sdk
          export ANDROID_SDK_ROOT=/tmp/android-sdk
          export PATH=$ANDROID_SDK_ROOT/build-tools/36.0.0:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp
          path: bin/*.apk
